### PR TITLE
Per #57, we shouldn't have been always merging into master. Merge into th

### PR DESCRIPTION
**Pull request by ChristopherMacGown**
Per #57, we shouldn't have been always merging into master. Merge into the requested branch instead.

### CODE REVIEW

**Comment by hub-cap** [comment]
+1. I can test this branch sometime today.

**Comment by hub-cap** [comment]
2 methods in client.py, base_branch and remote_branch contain the same docstring.

**Comment by hub-cap** [comment]
Ended up finally testing this. Seems good to go. Im able to use a non "master" branch and merge w/o issue.

**Comment by ChristopherMacGown** [comment]
LGTM

**Comment by ChristopherMacGown** [comment]
Build successful! Merged!

**Pull request closed without merging**
