### PR TITLE
Add pylint checking

### PR DESCRIPTION
**Pull request by ChristopherMacGown**
This is extra ugly, but I want it in before I switch how a run is done and add daemonization.

### CODE REVIEW

**Comment by larsbutler** [comment]
lgtm

**Comment by ChristopherMacGown** [comment]
Rejecting due to increased pylint score: 0 25

**Comment by ChristopherMacGown** [comment]
Rejecting due to increased pylint score: 25 0

**Comment by ChristopherMacGown** [comment]
Rejecting due to increased pylint score: 0 11

**Comment by ChristopherMacGown** [comment]
Build successful! Merged!

**Pull request closed without merging**
